# Generated by Django 4.2.3 on 2023-12-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0002_cmsuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isCopy',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
